"""CobbleVenture Event Script parsing and formatting tools."""

from .catalog import ResourceCatalog, ResourceKind, load_project_catalog
from .codec import (
    AstCodecError,
    WIRE_VERSION,
    decode_expression,
    decode_program,
    encode_expression,
    encode_program,
)
from .compiler import CvesCompilationError, IR_VERSION, compile_program
from .diagnostics import CvesSyntaxError, Diagnostic, SourcePosition, SourceSpan
from .editor import (
    CvesEditorConflict,
    diagnostic_document,
    editor_contract,
    list_scripts,
    load_script,
    parse_editor_expression,
    resolve_script_path,
    save_script,
    validate_ast,
    validate_source,
)
from .formatter import format_expression, format_program
from .lexer import Lexer, Token, TokenKind
from .migration import (
    BattleEventMigrationContract,
    ItemRewardMigrationContract,
    GymLeaderMigrationContract,
    SimpleDialogueMigrationContract,
    StarterEventMigrationContract,
    battle_event_contract_from_cves,
    battle_event_contract_from_v4,
    compare_battle_event_migration,
    compare_item_reward_migration,
    compare_gym_leader_migration,
    compare_simple_dialogue_migration,
    compare_starter_event_migration,
    item_reward_contract_from_cves,
    item_reward_contract_from_v4,
    gym_leader_contract_from_cves,
    gym_leader_contract_from_league,
    simple_dialogue_contract_from_cves,
    simple_dialogue_contract_from_v4,
    starter_event_contract_from_cves,
    starter_event_contract_from_v4,
)
from .parser import Parser, parse, parse_expression
from .project import CvesProjectError, ProjectArtifact, ProjectBuild, compile_project, write_project
from .semantic import SemanticValidator, validate

__all__ = [
    "CvesSyntaxError",
    "CvesProjectError",
    "CvesCompilationError",
    "CvesEditorConflict",
    "AstCodecError",
    "Diagnostic",
    "Lexer",
    "IR_VERSION",
    "ItemRewardMigrationContract",
    "GymLeaderMigrationContract",
    "BattleEventMigrationContract",
    "SimpleDialogueMigrationContract",
    "StarterEventMigrationContract",
    "battle_event_contract_from_cves",
    "battle_event_contract_from_v4",
    "compare_battle_event_migration",
    "Parser",
    "ProjectArtifact",
    "ProjectBuild",
    "ResourceCatalog",
    "ResourceKind",
    "SourcePosition",
    "SourceSpan",
    "SemanticValidator",
    "Token",
    "TokenKind",
    "WIRE_VERSION",
    "decode_program",
    "decode_expression",
    "diagnostic_document",
    "editor_contract",
    "encode_program",
    "encode_expression",
    "compile_program",
    "compile_project",
    "compare_item_reward_migration",
    "compare_gym_leader_migration",
    "compare_simple_dialogue_migration",
    "compare_starter_event_migration",
    "format_program",
    "format_expression",
    "list_scripts",
    "item_reward_contract_from_cves",
    "item_reward_contract_from_v4",
    "gym_leader_contract_from_cves",
    "gym_leader_contract_from_league",
    "simple_dialogue_contract_from_cves",
    "simple_dialogue_contract_from_v4",
    "starter_event_contract_from_cves",
    "starter_event_contract_from_v4",
    "load_project_catalog",
    "load_script",
    "parse",
    "parse_editor_expression",
    "parse_expression",
    "resolve_script_path",
    "save_script",
    "validate",
    "validate_ast",
    "validate_source",
    "write_project",
]
