# Cobbleventure Live NBT Editor shader defaults
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=24
shaderPack=ComplementaryReimagined_r5.3 + EuphoriaPatches_1.4.3
