modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Buizz"
description='''
Owns Cobbleventure's player menu, music, battle intros, and location announcements.
'''

[[mixins]]
config="cobbleventure_player_menu.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="${cobblemon_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemonxpbar"
type="optional"
versionRange="[1.0.5,1.1)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cobblenav"
type="optional"
versionRange="[2.3.3,2.4)"
ordering="AFTER"
side="CLIENT"
