modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Buizz"
description='''
Provides Cobbleventure battle progression, economy, recovery, and field-move rules.
'''

[[mixins]]
config="cobbleventure_adventure.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="${cobblemon_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobbledollars"
type="required"
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="rctapi"
type="required"
versionRange="[0.15.0-beta,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tbcs"
type="required"
versionRange="[0.14.1-beta,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobbleventure_player_menu"
type="required"
versionRange="${player_menu_version_range}"
ordering="AFTER"
side="BOTH"
