modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Buizz"
description='''웹에서 만든 프로필로 파괴 불가 커스텀 가챠 기계를 실행합니다.'''

[[mixins]]
config="cobbleventure_casino.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="${cobblemon_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemoncasino"
type="required"
versionRange="[2.0.0,3)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobbledollars"
type="required"
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playingcards"
type="required"
versionRange="[2.0.1,3)"
ordering="AFTER"
side="BOTH"
