plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'cobbleventure-player-menu'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

dependencies {
    compileOnly "maven.modrinth:cobblemon:${cobblemon_maven_version}"
}

neoForge {
    version = project.neo_version
    runs {
        client { client() }
        server { server() }
    }
    mods {
        "${mod_id}" { sourceSet(sourceSets.main) }
    }
}

processResources {
    def properties = [
        minecraft_version_range: minecraft_version_range,
        neo_version: neo_version,
        loader_version_range: loader_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
        cobblemon_version: cobblemon_version,
    ]
    inputs.properties properties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand properties
    }
}

tasks.register('cleanInstalledDevelopmentJars', Delete) {
    delete fileTree(rootProject.file('../../pack/overrides/development-placeholder/mods')) {
        include 'cobbleventure-player-menu-*.jar'
    }
}

tasks.register('installDevelopmentJar', Copy) {
    dependsOn jar
    dependsOn 'cleanInstalledDevelopmentJars'
    from jar
    into rootProject.file('../../pack/overrides/development-placeholder/mods')
}

tasks.named('build') {
    finalizedBy 'installDevelopmentJar'
}
